import { useNavigate } from "react-router-dom";
import { Award, ThumbsUp, AlertTriangle, MessageSquare, Cpu, ArrowRight } from "lucide-react";
import Layout from "../components/Layout";
import Card from "../components/Card";
import Button from "../components/Button";
import MatchRing from "../components/MatchRing";
import ProgressBar from "../components/ProgressBar";

const feedback = { overall: 78, communication: 82, technical: 74, strengths: ["Clear and structured explanations", "Good use of real examples", "Confident tone throughout"], weaknesses: ["Answers could be more concise", "Add more quantifiable outcomes"], recommendations: ["Practice the STAR method for behavioral questions", "Prepare 2–3 metrics-driven examples from past projects", "Work on pacing — aim for 90 second answers"] };

export default function InterviewFeedback() {
  const navigate = useNavigate();
  return <Layout><div className="mx-auto max-w-2xl"><div className="mb-8 flex flex-col items-center text-center"><div className="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-light-sage text-dark-green"><Award size={30} aria-hidden="true" /></div><p className="type-eyebrow">Practice review</p><h1 className="mt-2 type-page-title">Interview feedback</h1><p className="mt-3 type-supporting">Here&apos;s how you performed in your mock interview.</p></div><Card className="mb-6 flex flex-col items-center gap-4 sm:flex-row sm:justify-between" elevated><div className="flex items-center gap-4"><MatchRing value={feedback.overall} size={80} /><div><p className="type-meta">Overall score</p><p className="font-heading text-xl font-bold text-dark-green">Good performance</p></div></div><Button variant="outline" onClick={() => navigate("/mock-interview")}>Retake interview</Button></Card><div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2"><Card><div className="mb-3 flex items-center gap-2 text-dark-green"><MessageSquare size={17} aria-hidden="true" /><p className="text-base font-semibold">Communication</p></div><ProgressBar value={feedback.communication} label="Communication score" /><p className="mt-2 text-right text-sm font-semibold text-dark-green">{feedback.communication}%</p></Card><Card><div className="mb-3 flex items-center gap-2 text-dark-green"><Cpu size={17} aria-hidden="true" /><p className="text-base font-semibold">Technical knowledge</p></div><ProgressBar value={feedback.technical} label="Technical knowledge score" /><p className="mt-2 text-right text-sm font-semibold text-dark-green">{feedback.technical}%</p></Card></div><div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2"><Card><div className="mb-3 flex items-center gap-2 text-green"><ThumbsUp size={17} aria-hidden="true" /><p className="text-base font-semibold text-dark-green">Strengths</p></div><ul className="flex flex-col gap-2 text-base leading-7 text-text-dark">{feedback.strengths.map((strength) => <li key={strength}>• {strength}</li>)}</ul></Card><Card><div className="mb-3 flex items-center gap-2 text-coral"><AlertTriangle size={17} aria-hidden="true" /><p className="text-base font-semibold text-dark-green">Areas to improve</p></div><ul className="flex flex-col gap-2 text-base leading-7 text-text-dark">{feedback.weaknesses.map((weakness) => <li key={weakness}>• {weakness}</li>)}</ul></Card></div><Card className="mb-6"><h2 className="mb-3 font-heading text-xl font-bold text-dark-green">Recommendations</h2><ul className="flex flex-col gap-3 text-base leading-7 text-text-dark">{feedback.recommendations.map((recommendation) => <li key={recommendation} className="flex items-start gap-2"><span className="mt-3 h-1.5 w-1.5 shrink-0 rounded-full bg-coral" />{recommendation}</li>)}</ul></Card><Button variant="primary" size="lg" fullWidth icon={ArrowRight} iconPosition="right" onClick={() => navigate("/progress")}>View progress dashboard</Button></div></Layout>;
}
